version: '2'
services:
  master:
    build: .
    image: jenkins2
    restart: unless-stopped
    hostname: jenkins2
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home2:/var/jenkins_home

volumes:
  jenkins_home2:
